notifications:
  webhooks:
    - https://webhook.commit-email.info/
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update bundler
  - curl --silent --location
     https://raw.githubusercontent.com/groonga/groonga/master/data/travis/setup.sh |
      sh

